version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bullet-chess-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bullet_chess
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bullet-chess-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Optional: Redis GUI for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: bullet-chess-redis-gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    profiles:
      - gui

  # Optional: PostgreSQL GUI for development  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bullet-chess-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bullet-chess.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80"
    depends_on:
      - postgres
    profiles:
      - gui

volumes:
  postgres_data:
  redis_data: