apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bulletchess-tls
  namespace: bullet-chess
spec:
  secretName: bulletchess-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - bulletchess.org
  - www.bulletchess.org
  - api.bulletchess.org
  - ws.bulletchess.org

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@bulletchess.org  # Change to your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: istio
      selector:
        dnsNames:
        - bulletchess.org
        - www.bulletchess.org
        - api.bulletchess.org
        - ws.bulletchess.org

---
# Staging issuer for testing
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@bulletchess.org  # Change to your email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: istio