apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-cluster
  namespace: bullet-chess
spec:
  members: 3
  type: ReplicaSet
  version: "7.0"

  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: false  # Enable in production

  users:
  - name: chess-app
    db: bullet_chess
    passwordSecretRef:
      name: mongodb-credentials
    roles:
    - name: readWrite
      db: bullet_chess
    - name: clusterMonitor
      db: admin
    scramCredentialsSecretName: mongodb-scram

  additionalMongodConfig:
    storage:
      wiredTiger:
        engineConfig:
          journalCompressor: snappy
          directoryForIndexes: true
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true

    # Sharding preparation
    sharding:
      clusterRole: shardsvr

    # Performance settings for chess games
    net:
      maxIncomingConnections: 2000
      compression:
        compressors: "snappy,zstd"

    # Replication settings
    replication:
      oplogSizeMB: 10240  # 10GB oplog

    # Security
    security:
      authorization: enabled

  statefulSet:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mongodb-cluster-svc
                topologyKey: kubernetes.io/hostname
          containers:
          - name: mongod
            resources:
              requests:
                cpu: 2000m
                memory: 8Gi
              limits:
                cpu: 4000m
                memory: 16Gi
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: fast-ssd
          resources:
            requests:
              storage: 1000Gi

---
# MongoDB Sharding Configuration
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-configserver
  namespace: bullet-chess
spec:
  members: 3
  type: ReplicaSet
  version: "7.0"

  additionalMongodConfig:
    sharding:
      clusterRole: configsvr

  security:
    authentication:
      modes: ["SCRAM"]

  users:
  - name: chess-config
    db: admin
    passwordSecretRef:
      name: mongodb-config-credentials
    roles:
    - name: clusterAdmin
      db: admin
    - name: userAdminAnyDatabase
      db: admin

  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                cpu: 1000m
                memory: 4Gi
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: fast-ssd
          resources:
            requests:
              storage: 100Gi

---
# MongoDB Router (mongos)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-router
  namespace: bullet-chess
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-router
  template:
    metadata:
      labels:
        app: mongodb-router
    spec:
      containers:
      - name: mongos
        image: mongo:7.0
        command:
        - mongos
        args:
        - --configdb
        - rs0/mongodb-configserver-0.mongodb-configserver-svc.bullet-chess.svc.cluster.local:27017,mongodb-configserver-1.mongodb-configserver-svc.bullet-chess.svc.cluster.local:27017,mongodb-configserver-2.mongodb-configserver-svc.bullet-chess.svc.cluster.local:27017
        - --bind_ip_all
        - --port
        - "27017"
        - --logpath
        - /var/log/mongodb/mongos.log
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/mongodb
      volumes:
      - name: log-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-router-service
  namespace: bullet-chess
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb-router

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: bullet-chess
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password (change this!)

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config-credentials
  namespace: bullet-chess
type: Opaque
data:
  password: Y29uZmlncGFzcw==  # configpass (change this!)