apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: bullet-chess
spec:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  rabbitmq:
    additionalConfig: |
      # High-performance settings for 100K+ players
      tcp_listen_options.backlog = 4096
      tcp_listen_options.nodelay = true
      tcp_listen_options.linger.on = true
      tcp_listen_options.linger.timeout = 0

      # Memory and disk settings
      vm_memory_high_watermark.relative = 0.8
      disk_free_limit.relative = 1.0

      # Clustering
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      cluster_formation.node_cleanup.interval = 30
      cluster_formation.node_cleanup.only_log_warning = true
      cluster_partition_handling = autoheal

      # Queue settings for high throughput
      queue_master_locator = min-masters

      # Management plugin
      management.tcp.port = 15672

    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_peer_discovery_k8s
      - rabbitmq_prometheus
      - rabbitmq_stream
  persistence:
    storageClassName: fast-ssd
    storage: 100Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - rabbitmq-cluster
        topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster-service
  namespace: bullet-chess
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
  - port: 15692
    targetPort: 15692
    name: prometheus
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
---
# RabbitMQ Operator RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-cluster
  namespace: bullet-chess
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq-cluster
  namespace: bullet-chess
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq-cluster
  namespace: bullet-chess
subjects:
- kind: ServiceAccount
  name: rabbitmq-cluster
  namespace: bullet-chess
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-cluster