blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/CodeAndCoffeeGuy/bullet-chess/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/CodeAndCoffeeGuy/bullet-chess/blob/main/README.md
    about: Check the README for setup instructions and project information
